name: 'Build Lambda Layer'
description: 'Build and publish AWS Lambda layers for shared code or dependencies'

inputs:
  layer-name:
    description: 'Name of the Lambda layer'
    required: true
  layer-type:
    description: 'Type of layer: shared-code or dependencies'
    required: true
  source-paths:
    description: 'Comma-separated source paths for shared-code layers'
    required: false
  requirements-files:
    description: 'Comma-separated requirements files for dependency layers'
    required: false
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  aws-region:
    description: 'AWS region'
    required: true
  skip-du:
    description: 'Skip disk usage check'
    required: false
    default: 'false'

outputs:
  layer-arn:
    description: 'ARN of the published layer'
    value: ${{ steps.publish.outputs.layer-arn }}
  layer-version:
    description: 'Version number of the published layer'
    value: ${{ steps.publish.outputs.layer-version }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Create layer directory
      shell: bash
      run: |
        mkdir -p layer-build/python

    - name: Build shared code layer
      if: inputs.layer-type == 'shared-code'
      shell: bash
      run: |
        echo "Building shared code layer..."
        IFS=',' read -ra PATHS <<< "${{ inputs.source-paths }}"
        for path in "${PATHS[@]}"; do
          if [ -d "$path" ]; then
            echo "Copying $path to layer..."
            cp -r "$path" layer-build/python/
          else
            echo "Warning: Path $path does not exist"
          fi
        done

    - name: Build dependencies layer
      if: inputs.layer-type == 'dependencies'
      shell: bash
      run: |
        echo "Building dependencies layer..."
        IFS=',' read -ra FILES <<< "${{ inputs.requirements-files }}"
        
        # Create a combined requirements file
        > combined-requirements.txt
        for file in "${FILES[@]}"; do
          if [ -f "$file" ]; then
            echo "Adding requirements from $file..."
            cat "$file" >> combined-requirements.txt
          else
            echo "Warning: Requirements file $file does not exist"
          fi
        done
        
        # Install dependencies
        if [ -s combined-requirements.txt ]; then
          echo "Installing Python dependencies..."
          pip install -r combined-requirements.txt -t layer-build/python/
        else
          echo "No requirements to install"
        fi
        
        # Clean up
        rm -f combined-requirements.txt

    - name: Clean up layer directory
      shell: bash
      run: |
        echo "Cleaning up layer directory..."
        cd layer-build/python
        
        # Remove unnecessary files
        find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
        find . -name "*.pyc" -delete 2>/dev/null || true
        find . -name "*.pyo" -delete 2>/dev/null || true
        find . -name "*.dist-info" -type d -exec rm -rf {} + 2>/dev/null || true
        find . -name "*.egg-info" -type d -exec rm -rf {} + 2>/dev/null || true
        
        # Remove test directories
        find . -type d -name "tests" -exec rm -rf {} + 2>/dev/null || true
        find . -type d -name "test" -exec rm -rf {} + 2>/dev/null || true
        
        cd ../..

    - name: Check layer size
      if: inputs.skip-du != 'true'
      shell: bash
      run: |
        echo "Checking layer size..."
        LAYER_SIZE=$(du -sh layer-build | cut -f1)
        echo "Layer size: $LAYER_SIZE"
        
        # Check if size is reasonable (warn if > 200MB, fail if > 250MB)
        LAYER_SIZE_BYTES=$(du -sb layer-build | cut -f1)
        if [ "$LAYER_SIZE_BYTES" -gt 262144000 ]; then
          echo "Error: Layer size ($LAYER_SIZE) exceeds 250MB limit"
          exit 1
        elif [ "$LAYER_SIZE_BYTES" -gt 209715200 ]; then
          echo "Warning: Layer size ($LAYER_SIZE) is approaching 250MB limit"
        fi

    - name: Create layer zip
      shell: bash
      run: |
        echo "Creating layer zip file..."
        cd layer-build
        zip -r ../layer.zip . -q
        cd ..
        
        ZIP_SIZE=$(du -sh layer.zip | cut -f1)
        echo "Zip file size: $ZIP_SIZE"

    - name: Publish layer
      id: publish
      shell: bash
      run: |
        echo "Publishing layer ${{ inputs.layer-name }}..."
        
        # Create layer description
        DESCRIPTION="Layer for ${{ inputs.layer-name }} (type: ${{ inputs.layer-type }})"
        if [ "${{ inputs.layer-type }}" = "shared-code" ]; then
          DESCRIPTION="$DESCRIPTION - Sources: ${{ inputs.source-paths }}"
        else
          DESCRIPTION="$DESCRIPTION - Requirements: ${{ inputs.requirements-files }}"
        fi
        
        # Publish the layer
        RESULT=$(aws lambda publish-layer-version \
          --layer-name "${{ inputs.layer-name }}" \
          --description "$DESCRIPTION" \
          --zip-file fileb://layer.zip \
          --compatible-runtimes python${{ inputs.python-version }} \
          --region "${{ inputs.aws-region }}" \
          --output json)
        
        # Extract ARN and version
        LAYER_ARN=$(echo "$RESULT" | jq -r '.LayerArn')
        LAYER_VERSION=$(echo "$RESULT" | jq -r '.Version')
        LAYER_VERSION_ARN=$(echo "$RESULT" | jq -r '.LayerVersionArn')
        
        echo "Layer published successfully!"
        echo "Layer ARN: $LAYER_VERSION_ARN"
        echo "Version: $LAYER_VERSION"
        
        # Set outputs
        echo "layer-arn=$LAYER_VERSION_ARN" >> "$GITHUB_OUTPUT"
        echo "layer-version=$LAYER_VERSION" >> "$GITHUB_OUTPUT"

    - name: Cleanup
      if: always()
      shell: bash
      run: |
        echo "Cleaning up build artifacts..."
        rm -rf layer-build layer.zip 2>/dev/null || true