// PDF Exporter Service - Generate professional contract analysis reports
// Uses jsPDF for PDF generation

class PDFExporter {
  constructor() {
    this.doc = null;
    this.pageWidth = 210; // A4 width in mm
    this.pageHeight = 297; // A4 height in mm
    this.margin = 20;
    this.currentY = 20;
    this.lineHeight = 7;
    this.colors = {
      primary: [0, 102, 204],      // Blue
      success: [34, 139, 34],       // Green
      warning: [255, 140, 0],       // Orange
      danger: [220, 20, 60],        // Red
      gray: [128, 128, 128],
      darkGray: [64, 64, 64],
      lightGray: [200, 200, 200]
    };
  }

  /**
   * Generate PDF report from analysis results
   */
  async generateReport(results, metadata = {}) {
    // Initialize jsPDF
    const { jsPDF } = window.jspdf;
    this.doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    this.currentY = this.margin;

    try {
      // Page 1: Cover page
      this.addCoverPage(metadata, results.risk_summary);

      // Page 2: Executive Summary (Section I)
      this.addNewPage();
      this.addExecutiveSummary(results.executive_summary, results.risk_summary);

      // Page 3+: Risk Summary Dashboard
      this.addNewPage();
      this.addRiskDashboard(results.risk_summary, results.sections);

      // Detailed Section Analysis
      const sectionKeys = ['section_ii', 'section_iii', 'section_iv', 'section_v', 'section_vi', 'section_vii'];

      for (const sectionKey of sectionKeys) {
        if (results.sections[sectionKey]) {
          this.addNewPage();
          this.addSectionAnalysis(sectionKey, results.sections[sectionKey]);
        }
      }

      // Final page: Recommendations
      this.addNewPage();
      this.addRecommendations(results);

      // Add footer to all pages
      this.addFooters(metadata);

      // Return the PDF
      return this.doc;

    } catch (error) {
      console.error('PDF generation failed:', error);
      throw new Error(`PDF generation failed: ${error.message}`);
    }
  }

  /**
   * Add cover page
   */
  addCoverPage(metadata, riskSummary) {
    // Company logo placeholder (text-based)
    this.doc.setFontSize(36);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...this.colors.primary);
    this.doc.text('APS', this.margin, this.currentY);

    this.currentY += 10;
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...this.colors.darkGray);
    this.doc.text('Atlantic Pipe Services', this.margin, this.currentY);

    // Title
    this.currentY = 80;
    this.doc.setFontSize(28);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(0, 0, 0);
    this.doc.text('Contract Risk Analysis', this.margin, this.currentY);

    this.currentY += 12;
    this.doc.setFontSize(20);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text('CR2A Report', this.margin, this.currentY);

    // Risk badge
    this.currentY += 25;
    const riskLevel = riskSummary?.overallRisk || 'Unknown';
    const riskColor = this.getRiskColor(riskLevel);

    this.doc.setFillColor(...riskColor);
    this.doc.rect(this.margin, this.currentY, 60, 15, 'F');
    this.doc.setTextColor(255, 255, 255);
    this.doc.setFontSize(16);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(`${riskLevel.toUpperCase()} RISK`, this.margin + 4, this.currentY + 10);

    // Metadata
    this.currentY = 160;
    this.doc.setTextColor(...this.colors.darkGray);
    this.doc.setFontSize(11);
    this.doc.setFont('helvetica', 'normal');

    const metadataItems = [
      ['Contract ID:', metadata.contract_id || 'N/A'],
      ['Project Title:', metadata.project_title || 'N/A'],
      ['Contract Owner:', metadata.owner || 'N/A'],
      ['Analysis Date:', new Date(metadata.analysis_date || Date.now()).toLocaleDateString()],
      ['Total Findings:', riskSummary?.totalFindings || 0]
    ];

    metadataItems.forEach(([label, value]) => {
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(label, this.margin, this.currentY);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(String(value), this.margin + 45, this.currentY);
      this.currentY += 8;
    });

    // Footer text
    this.currentY = this.pageHeight - 30;
    this.doc.setFontSize(9);
    this.doc.setTextColor(...this.colors.gray);
    this.doc.text('Generated by CR2A v2.0 - GitHub Pages Edition', this.margin, this.currentY);
    this.doc.text('Confidential - For Internal Use Only', this.margin, this.currentY + 5);
  }

  /**
   * Add executive summary page
   */
  addExecutiveSummary(executiveSummary, riskSummary) {
    this.addSectionHeader('Executive Summary');

    // Overall Assessment
    this.addSubheader('Overall Assessment');
    const assessment = executiveSummary?.overall_assessment || 
                      executiveSummary?.fallback?.overall_assessment ||
                      'No executive summary available';
    this.addParagraph(assessment);

    // Risk Distribution
    this.addSubheader('Risk Distribution');
    const dist = riskSummary?.distribution || { High: 0, Medium: 0, Low: 0 };

    this.addRiskBar('High Risk', dist.High, this.colors.danger);
    this.addRiskBar('Medium Risk', dist.Medium, this.colors.warning);
    this.addRiskBar('Low Risk', dist.Low, this.colors.success);

    this.currentY += 5;

    // Critical Findings
    this.addSubheader('Critical Findings');
    const findings = executiveSummary?.critical_findings || 
                    executiveSummary?.fallback?.critical_findings || [];

    if (findings.length > 0) {
      this.addBulletList(findings.slice(0, 5));
    } else {
      this.addParagraph('No critical findings identified.');
    }

    // Key Recommendations
    this.addSubheader('Key Recommendations');
    const recommendations = executiveSummary?.key_recommendations ||
                           executiveSummary?.fallback?.key_recommendations || [];

    if (recommendations.length > 0) {
      this.addBulletList(recommendations.slice(0, 5));
    } else {
      this.addParagraph('No specific recommendations at this time.');
    }
  }

  /**
   * Add risk dashboard
   */
  addRiskDashboard(riskSummary, sections) {
    this.addSectionHeader('Risk Analysis Dashboard');

    // Summary stats
    this.addSubheader('Summary Statistics');

    const stats = [
      ['Overall Risk Level', riskSummary?.overallRisk || 'Unknown'],
      ['Total Findings', riskSummary?.totalFindings || 0],
      ['High Risk Items', riskSummary?.distribution?.High || 0],
      ['Medium Risk Items', riskSummary?.distribution?.Medium || 0],
      ['Low Risk Items', riskSummary?.distribution?.Low || 0]
    ];

    this.addKeyValueTable(stats);

    this.currentY += 5;

    // Section breakdown
    this.addSubheader('Risk by Section');

    const sectionNames = {
      section_ii: 'Administrative & Commercial',
      section_iii: 'Technical & Performance',
      section_iv: 'Legal Risk & Enforcement',
      section_v: 'Regulatory & Compliance',
      section_vi: 'Data Security & Technology',
      section_vii: 'Supplemental Risk Areas'
    };

    Object.keys(sectionNames).forEach(key => {
      if (sections[key]) {
        const findings = sections[key].findings || [];
        const high = findings.filter(f => f.risk_level === 'High').length;
        const medium = findings.filter(f => f.risk_level === 'Medium').length;
        const low = findings.filter(f => f.risk_level === 'Low').length;

        this.doc.setFontSize(10);
        this.doc.setFont('helvetica', 'bold');
        this.doc.setTextColor(0, 0, 0);
        this.doc.text(sectionNames[key], this.margin, this.currentY);

        this.doc.setFont('helvetica', 'normal');
        this.doc.setFontSize(9);
        this.doc.setTextColor(...this.colors.gray);
        this.doc.text(`H: ${high}  M: ${medium}  L: ${low}`, this.pageWidth - this.margin - 30, this.currentY);

        this.currentY += 6;

        if (this.currentY > this.pageHeight - 30) {
          this.addNewPage();
        }
      }
    });
  }

  /**
   * Add detailed section analysis
   */
  addSectionAnalysis(sectionKey, sectionData) {
    const sectionNames = {
      section_ii: 'Section II: Administrative & Commercial',
      section_iii: 'Section III: Technical & Performance',
      section_iv: 'Section IV: Legal Risk & Enforcement',
      section_v: 'Section V: Regulatory & Compliance',
      section_vi: 'Section VI: Data Security & Technology',
      section_vii: 'Section VII: Supplemental Risk Areas'
    };

    this.addSectionHeader(sectionNames[sectionKey] || sectionKey);

    const findings = sectionData.findings || [];

    if (findings.length === 0) {
      this.addParagraph('No findings recorded for this section.');
      return;
    }

    // Group by risk level
    const highRisk = findings.filter(f => f.risk_level === 'High');
    const mediumRisk = findings.filter(f => f.risk_level === 'Medium');
    const lowRisk = findings.filter(f => f.risk_level === 'Low');

    // High risk findings
    if (highRisk.length > 0) {
      this.addSubheader('High Risk Items', this.colors.danger);
      highRisk.forEach(finding => {
        this.addFinding(finding, 'High');
      });
    }

    // Medium risk findings
    if (mediumRisk.length > 0) {
      this.addSubheader('Medium Risk Items', this.colors.warning);
      mediumRisk.forEach(finding => {
        this.addFinding(finding, 'Medium');
      });
    }

    // Low risk findings (summary only to save space)
    if (lowRisk.length > 0) {
      this.addSubheader('Low Risk Items', this.colors.success);
      this.doc.setFontSize(9);
      this.doc.setTextColor(...this.colors.gray);
      this.doc.text(`${lowRisk.length} low-risk items identified. Details available in full analysis data.`, 
                    this.margin, this.currentY);
      this.currentY += 7;
    }
  }

  /**
   * Add individual finding
   */
  addFinding(finding, riskLevel) {
    if (this.currentY > this.pageHeight - 40) {
      this.addNewPage();
    }

    // Item name with risk badge
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(0, 0, 0);
    this.doc.text(`• ${finding.item_name}`, this.margin, this.currentY);

    // Risk badge
    const badgeX = this.pageWidth - this.margin - 25;
    const riskColor = this.getRiskColor(riskLevel);
    this.doc.setFillColor(...riskColor);
    this.doc.rect(badgeX, this.currentY - 3, 20, 5, 'F');
    this.doc.setFontSize(7);
    this.doc.setTextColor(255, 255, 255);
    this.doc.text(riskLevel.toUpperCase(), badgeX + 2, this.currentY);

    this.currentY += 6;

    // Status
    if (finding.status) {
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...this.colors.gray);
      this.doc.text(`Status: ${finding.status}`, this.margin + 5, this.currentY);
      this.currentY += 5;
    }

    // Details
    if (finding.details) {
      this.doc.setFontSize(9);
      this.doc.setTextColor(...this.colors.darkGray);
      const detailsText = this.wrapText(finding.details, this.pageWidth - 2 * this.margin - 10);
      detailsText.slice(0, 3).forEach(line => { // Limit to 3 lines
        this.doc.text(line, this.margin + 5, this.currentY);
        this.currentY += 4.5;
      });
    }

    // Recommendations
    if (finding.recommendations) {
      this.doc.setFont('helvetica', 'italic');
      this.doc.setTextColor(...this.colors.primary);
      const recText = this.wrapText(`→ ${finding.recommendations}`, this.pageWidth - 2 * this.margin - 10);
      recText.slice(0, 2).forEach(line => { // Limit to 2 lines
        this.doc.text(line, this.margin + 5, this.currentY);
        this.currentY += 4.5;
      });
    }

    this.currentY += 5;
  }

  /**
   * Add recommendations summary
   */
  addRecommendations(results) {
    this.addSectionHeader('Summary of Recommendations');

    // Collect all recommendations
    const allRecommendations = [];

    Object.values(results.sections || {}).forEach(section => {
      (section.findings || []).forEach(finding => {
        if (finding.recommendations && finding.risk_level === 'High') {
          allRecommendations.push({
            item: finding.item_name,
            recommendation: finding.recommendations,
            risk: finding.risk_level
          });
        }
      });
    });

    if (allRecommendations.length === 0) {
      this.addParagraph('No high-priority recommendations identified.');
      return;
    }

    this.addSubheader('High Priority Actions');

    allRecommendations.slice(0, 10).forEach((rec, idx) => {
      if (this.currentY > this.pageHeight - 30) {
        this.addNewPage();
      }

      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(0, 0, 0);
      this.doc.text(`${idx + 1}. ${rec.item}`, this.margin, this.currentY);
      this.currentY += 5;

      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...this.colors.darkGray);
      const recLines = this.wrapText(rec.recommendation, this.pageWidth - 2 * this.margin - 5);
      recLines.slice(0, 2).forEach(line => {
        this.doc.text(line, this.margin + 5, this.currentY);
        this.currentY += 4.5;
      });

      this.currentY += 3;
    });
  }

  /**
   * Helper: Add section header
   */
  addSectionHeader(title) {
    if (this.currentY > this.pageHeight - 50) {
      this.addNewPage();
    }

    this.doc.setFontSize(16);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...this.colors.primary);
    this.doc.text(title, this.margin, this.currentY);

    this.currentY += 3;
    this.doc.setDrawColor(...this.colors.primary);
    this.doc.setLineWidth(0.5);
    this.doc.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY);

    this.currentY += 8;
  }

  /**
   * Helper: Add subheader
   */
  addSubheader(title, color = null) {
    if (this.currentY > this.pageHeight - 30) {
      this.addNewPage();
    }

    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...(color || this.colors.darkGray));
    this.doc.text(title, this.margin, this.currentY);
    this.currentY += 7;
  }

  /**
   * Helper: Add paragraph
   */
  addParagraph(text) {
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...this.colors.darkGray);

    const lines = this.wrapText(text, this.pageWidth - 2 * this.margin);
    lines.forEach(line => {
      if (this.currentY > this.pageHeight - 30) {
        this.addNewPage();
      }
      this.doc.text(line, this.margin, this.currentY);
      this.currentY += 5;
    });

    this.currentY += 3;
  }

  /**
   * Helper: Add bullet list
   */
  addBulletList(items) {
    items.forEach(item => {
      if (this.currentY > this.pageHeight - 30) {
        this.addNewPage();
      }

      this.doc.setFontSize(10);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...this.colors.darkGray);

      const lines = this.wrapText(`• ${item}`, this.pageWidth - 2 * this.margin - 5);
      lines.forEach(line => {
        this.doc.text(line, this.margin, this.currentY);
        this.currentY += 5;
      });
    });

    this.currentY += 2;
  }

  /**
   * Helper: Add key-value table
   */
  addKeyValueTable(items) {
    items.forEach(([key, value]) => {
      if (this.currentY > this.pageHeight - 30) {
        this.addNewPage();
      }

      this.doc.setFontSize(10);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...this.colors.darkGray);
      this.doc.text(`${key}:`, this.margin, this.currentY);

      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(0, 0, 0);
      this.doc.text(String(value), this.margin + 60, this.currentY);

      this.currentY += 6;
    });
  }

  /**
   * Helper: Add risk bar
   */
  addRiskBar(label, count, color) {
    if (this.currentY > this.pageHeight - 30) {
      this.addNewPage();
    }

    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(0, 0, 0);
    this.doc.text(label, this.margin, this.currentY);

    const barX = this.margin + 50;
    const barWidth = Math.min(count * 3, 100);

    this.doc.setFillColor(...color);
    this.doc.rect(barX, this.currentY - 3, barWidth, 5, 'F');

    this.doc.setFontSize(9);
    this.doc.text(String(count), barX + barWidth + 3, this.currentY);

    this.currentY += 8;
  }

  /**
   * Helper: Get risk color
   */
  getRiskColor(riskLevel) {
    switch (riskLevel?.toLowerCase()) {
      case 'high': return this.colors.danger;
      case 'medium': return this.colors.warning;
      case 'low': return this.colors.success;
      default: return this.colors.gray;
    }
  }

  /**
   * Helper: Wrap text to fit width
   */
  wrapText(text, maxWidth) {
    const words = text.split(' ');
    const lines = [];
    let currentLine = '';

    words.forEach(word => {
      const testLine = currentLine + (currentLine ? ' ' : '') + word;
      const testWidth = this.doc.getTextWidth(testLine);

      if (testWidth > maxWidth && currentLine) {
        lines.push(currentLine);
        currentLine = word;
      } else {
        currentLine = testLine;
      }
    });

    if (currentLine) {
      lines.push(currentLine);
    }

    return lines;
  }

  /**
   * Helper: Add new page
   */
  addNewPage() {
    this.doc.addPage();
    this.currentY = this.margin;
  }

  /**
   * Helper: Add footers to all pages
   */
  addFooters(metadata) {
    const pageCount = this.doc.internal.getNumberOfPages();

    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i);

      this.doc.setFontSize(8);
      this.doc.setTextColor(...this.colors.gray);
      this.doc.setFont('helvetica', 'normal');

      // Left footer
      this.doc.text(
        `CR2A Analysis - ${metadata.contract_id || 'Unknown'}`,
        this.margin,
        this.pageHeight - 10
      );

      // Right footer
      this.doc.text(
        `Page ${i} of ${pageCount}`,
        this.pageWidth - this.margin - 20,
        this.pageHeight - 10
      );
    }
  }

  /**
   * Save PDF to file
   */
  save(filename = 'cr2a-analysis.pdf') {
    if (!this.doc) {
      throw new Error('No document to save');
    }
    this.doc.save(filename);
  }

  /**
   * Get PDF as blob
   */
  getBlob() {
    if (!this.doc) {
      throw new Error('No document available');
    }
    return this.doc.output('blob');
  }
}

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = PDFExporter;
}
